#test ederken kullanýlacak http requestlerini buraya ekleyebilirsiniz postman'a ihtiyaç duymadan buradan request gönderebiliriz.#
#RestClient

@baseAddress = http://localhost:5225
@categoryId=08dd5440-129f-a2c8-00ff-7ee97aa70000
@courseId=08dd58a4-a024-3b76-00ff-7ee97aa70000
@userId=7aa70000-7ee9-00ff-d127-08dd596e0e62

GET {{baseAddress}}/api/categories
Accept: application/json
###
POST {{baseAddress}}/api/categories
Accept: application/json
Content-Type: application/json
{
  "name":"Category 1"
}
###
GET {{baseAddress}}/api/categories/{{categoryId}}
Accept: application/json
###

POST {{baseAddress}}/api/courses
Accept: application/json
Content-Type: application/json
{
  "name": "New Course",
  "description": "Description",
  "price": 100.00,  
  "ImageUrl": "picture.jpg",  
  "categoryId": "{{categoryId}}"
}
###
###
PUT {{baseAddress}}/api/courses
Accept: application/json
Content-Type: application/json
{
  "Id":"{{courseId}}",
  "name": "New Course",
  "description": "DescriptionNews",
  "price": 300.00,  
  "ImageUrl": "picture.jpg",  
  "categoryId": "{{categoryId}}"
}
###
GET {{baseAddress}}/api/courses
Accept: application/json
###
GET {{baseAddress}}/api/courses/{{courseId}}
Accept: application/json
###
###
Delete {{baseAddress}}/api/courses/{{courseId}}
Accept: application/json
###
###
GET {{baseAddress}}/api/courses/user/{{userId}}
Accept: application/json
###